title: James Blog
author: James Chen
email: banger007@qq.com
description: > # this means to ignore newlines until "baseurl:"
I'm working on building up this blog to note/share something usefull/helpfull. Please let me know if any sugguestion.

# social links
twitter_username: TBD # DO NOT include the @ character, or else the build will fail!
github_username:  JamesChenPage # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
